spring.application.name=studentmanagement

spring.datasource.url=jdbc:postgresql://dpg-d6o4879aae7s73brtjq0-a.singapore-postgres.render.com/sms_axsg
spring.datasource.username=sms_axsg_user
spring.datasource.password=F9u87rQFUtVwbBRu8I2gyOdOkA37M6jw
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.web.resources.static-locations=classpath:/static/
spring.web.resources.cache.period=3600

server.port=${PORT:8080}